# MLflow configuration
mlflow:
  image:
    repository: python
    tag: "3.9"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  server:
    host: "0.0.0.0"
    port: 5000
    workers: 2
  
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# External PostgreSQL configuration
postgresql:
  host: ""          # REQUIRED: PostgreSQL host
  port: 5432
  database: "mlflow"
  username: "mlflow"
  password: ""      # REQUIRED: PostgreSQL password

# External MinIO configuration  
minio:
  endpoint: ""      # REQUIRED: MinIO endpoint
  port: 9000
  secure: false     # true for HTTPS, false for HTTP
  bucket: "mlflow-artifacts"
  region: "us-east-1"
  accessKey: ""     # REQUIRED: MinIO access key
  secretKey: ""     # REQUIRED: MinIO secret key

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 5000

# OpenShift Route configuration
route:
  enabled: true
  host: ""          # Leave empty for auto-generated host
  tls:
    enabled: true
    termination: edge

# Security Context for OpenShift (compatible with restricted-v2 SCC)
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  seccompProfile:
    type: RuntimeDefault

# Pod Security Context (sin fsGroup para evitar problemas con restricted-v2)
podSecurityContext: {}