apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-secret
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.postgresql.password | b64enc | quote }}
  minio-access-key: {{ .Values.minio.accessKey | b64enc | quote }}
  minio-secret-key: {{ .Values.minio.secretKey | b64enc | quote }}
---
{{- if .Values.mlflow.oauth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-oauth-secret
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ include "mlflow.sessionSecret" . | quote }}
  cookie-secret: {{ include "mlflow.cookieSecret" . | quote }}
{{- end }}