apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
---
{{- if .Values.mlflow.oauth.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow.fullname" . }}-oauth
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.mlflow: |
      {
        "kind": "OAuthRedirectReference",
        "apiVersion": "v1",
        "reference": {
          "kind": "Route",
          "name": "{{ include "mlflow.fullname" . }}"
        }
      }
{{- end }}